### PR TITLE
Fix non-ASCII last name

### PR DESCRIPTION
**Pull request by Juanlu001**
In case I'm still in time!

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Oy, the git diff !

Probably not too late for an eventual fix, although I can't actually see the fix easily. I believe Matt generates the author list programmatically from form data.

**Comment by mdhaber** [comment]
@Juanlu001 please let us know what needs to be changed. We will not merge this; it just needs to be adjusted in our spreadsheet.

**Comment by ilayn** [comment]
Do you mind making the list newline broken when repopulating it? TeX doesn't care and will make things a bit more visible. 

Nano-nitpick: Two letter TeX commands are deprecated long time ago. Either use `\textbf{...}` for short items or `{\bfseries ... }` for the long groups, especially important if you are going to mix other font shapes.

**Comment by Juanlu001** [comment]
Oops, didn't realize the diff...

It's `Rodr\'iguez$^{70}`, my second last name, instead of `Rodr'iguez$^{70}`, which is what I typed in the form.

**Comment by mdhaber** [comment]
@Juanlu001 all set

**Comment by mdhaber** [comment]
@ilayn next version will have line breaks and `bfseries`

**Pull request closed without merging**
