### PR TITLE
MAINT: reviewer comment re: test benefits

### LINKED ISSUE #229: Comment to Address: Explain Benefit of Unit Testing
> Page 11. From the text, it is unclear why testing and code coverage are useful metrics. Some mention of correctness is likely required and could be a good time to mention that these metrics give both contributors courage that they are not breaking the package and maintainers some faith that a contribution does not harm the package.

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #229

* address *Nature Methods* reviewer comment requesting
a brief explanation of the benefits of unit testing
& test line coverage before we dive into the details
of our testing infrastructure

### CODE REVIEW

**Comment by stefanv** [comment]
Looks like I cannot push to this branch, so I'll suggest a diff here:

```diff
diff --git a/scipy-1.0/paper.tex b/scipy-1.0/paper.tex
index 213d258..f2e5ed6 100644
--- a/scipy-1.0/paper.tex
+++ b/scipy-1.0/paper.tex
@@ -878,11 +878,11 @@ and the multinomial distribution in \texttt{scipy.stats.multinomial}
 \subsubsection*{Test suite}
 
 Test-driven development has been described as a way to manage fear and
-uncertainity when making code changes\cite{TDD-Beck}. For each component of SciPy, we write multiple small executable
-tests that verify its intended behavior. The collection of these, known as a \emph{test suite}, increases confidence in
-the correctness and accuracy of the library, and lets us make code modifications known not to alter desired behavior. Monitoring the number of lines
-of code in SciPy covered by unit tests is one way we maintain
-some certainty that changes and new features are correctly implemented.
+uncertainity when making code changes\cite{TDD-Beck}. We write small executable
+tests that verify the correctness of some component of our code, building this
+up over time to increase our confidence. Monitoring the number of lines
+of code in SciPy that are properly covered by unit tests is one way we maintain
+some certainty that changes and new features are not harmful.
 The SciPy test suite is orchestrated by a continuous integration matrix that
 includes POSIX and Windows (32/64-bit) platforms managed by Travis CI and
 AppVeyor, respectively. Our tests cover Python versions 2.7, 3.4, 3.5, 3.6, and
```

**Comment by stefanv** [comment]
I don't have push access to this branch, so here is a suggested change with some minor rewording:

```diff
diff --git a/scipy-1.0/paper.tex b/scipy-1.0/paper.tex
index f2e5ed6..213d258 100644
--- a/scipy-1.0/paper.tex
+++ b/scipy-1.0/paper.tex
@@ -878,11 +878,11 @@ and the multinomial distribution in \texttt{scipy.stats.multinomial}
 \subsubsection*{Test suite}
 
 Test-driven development has been described as a way to manage fear and
-uncertainity when making code changes\cite{TDD-Beck}. We write small executable
-tests that verify the correctness of some component of our code, building this
-up over time to increase our confidence. Monitoring the number of lines
-of code in SciPy that are properly covered by unit tests is one way we maintain
-some certainty that changes and new features are not harmful.
+uncertainity when making code changes\cite{TDD-Beck}. For each component of SciPy, we write multiple small executable
+tests that verify its intended behavior. The collection of these, known as a \emph{test suite}, increases confidence in
+the correctness and accuracy of the library, and lets us make code modifications known not to alter desired behavior. Monitoring the number of lines
+of code in SciPy covered by unit tests is one way we maintain
+some certainty that changes and new features are correctly implemented.
 The SciPy test suite is orchestrated by a continuous integration matrix that
 includes POSIX and Windows (32/64-bit) platforms managed by Travis CI and
 AppVeyor, respectively. Our tests cover Python versions 2.7, 3.4, 3.5, 3.6, and
```

**Comment by tylerjereddy** [comment]
Thanks Stefan, I've applied your patch directly with `git apply`

**Comment by mdhaber** [comment]
Thanks @tylerjereddy @stefanv

**Pull request merged**
