### PR TITLE
Author list updates

### PR DESCRIPTION
**Pull request by mdhaber**
Addresses #202, #207, #210, #217
@musically-ut, @FabricioS, @charris, @VarIr Please check that your proposed changes have been addressed correctly.

### CODE REVIEW

**Comment by FabricioS** [comment]
It's OK concerning my PR. Thank you

**Comment by musically-ut** [comment]
Looks good to me.

Thanks!

**Comment by mdhaber** [comment]
@charris @VarIr We'll need to merge this soon, so please take a look if you have a chance.

**Comment by VarIr** [comment]
LGTM

**Comment by mdhaber** [comment]
I double checked that this addresses #210 for @charris, and I want to make sure this gets in before we submit, so merging.

**Pull request merged**
