### PR TITLE
Change roadmap summary of ndimage

### PR DESCRIPTION
**Pull request by stefanv**
The roadmap description for `ndimage` recently changed: https://scipy.github.io/devdocs/roadmap-detailed.html

Updated the paper summary accordingly.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
I think the Table is meant to reflect the state of the roadmap at 1.0 release point rather than at 1.3.0dev.

Otherwise, the table caption needs to be changed & other entries probably need updating if others agree to use more recent roadmap changes.

**Comment by mdhaber** [comment]
I agree that the table was intended to be the 1.0 roadmap. Could indicate in the caption where the current roadmap can be found.
@rgommers would you make the call on this?

**Comment by tylerjereddy** [comment]
This is a pretty minor adjustment / refinement in priority so I'll just merge it.

I think @mdhaber & I agree that we shouldn't refactor the whole table for 1.3.0dev though.

**Comment by tylerjereddy** [comment]
Thanks Stefan

**Comment by rgommers** [comment]
+1 current state LGTM

**Pull request merged**
