### PR TITLE
Language Breakdown Figure -> Table?

### PR DESCRIPTION
**Pull request by mdhaber**
Exhibit A (#114 )
image

Exhibit B (this PR, as suggested by @ilayn in #111)
image

Votes?

### CODE REVIEW

**Comment by mdhaber** [comment]
@ilayn tests complain about siunitx. Thoughts?

**Comment by ilayn** [comment]
The package is not installed somehow even though it should be [a part of TeXLive ](https://ctan.org/pkg/siunitx?lang=en)

**Comment by jarrodmillman** [comment]
I prefer the table.

**Comment by tylerjereddy** [comment]
Oy, are we still debating this thing!

**Comment by ilayn** [comment]
Parking the debate aside for a moment, it looks like the .circleci file requires 

```bash
- command: sudo apt install texlive-scientific
``` 
after line 8 `checkout`. I used `siunitx` for aligning the second column at the decimal point but if it turns out to slow things down I can manually do that.  It's not really a blocking issue. But if we have a lot of units to be entered this package is the de facto standard.

About the figure, table thingy; my argument is that the programmer audience would definitely know these languages thus don't need the logo and the non-programmer audience won't recognize the logos. Hence either way it seems like they don't inform the interested reader.

**Comment by WarrenWeckesser** [comment]
B (the table).

**Comment by mdhaber** [comment]
Ok, votes are for the table. I'll try to get this building then merge.

**Comment by mdhaber** [comment]
@ilayn Did I do this right? Didn't seem to work.

**Comment by mdhaber** [comment]
Hey @ilayn thoughts on how to fix this?

**Comment by ilayn** [comment]
Hmm, I guess then it has to go to that `run` block. We just need another line of command to be run and I am not sure if we even need sudo rights.

**Comment by mdhaber** [comment]
@ilayn "Unable to locate package texlive-scientific"
Can we do this without texlive-scientific?

**Comment by ilayn** [comment]
I don't really know where it is. Should be in this https://packages.ubuntu.com/disco/texlive-science but apparently something has changed according to these comments https://askubuntu.com/questions/369268/missing-sty-package. You can remove the S column and make it a regular TeX table if you wish, so that we can merge this.

**Comment by mdhaber** [comment]
@ilayn Can you make the modification and I'll copy-paste?

**Comment by ilayn** [comment]
Ah nice, thank you @mdhaber, @jarrodmillman

**Pull request closed without merging**
