### PR TITLE
[WIP] ENH: Optimize Section

### PR DESCRIPTION
**Pull request by mdhaber**
Still don't know what I'm doing with git. Just trying to figure out how to add my contributions to the paper.

I'd appreciate feedback to any questions asked in the text.

### CODE REVIEW

**Comment by mdhaber** [comment]
The most important questions right now:

- Is this an appropriate way of breaking down the optimization subsection?
- Does the introductory text written for root finding provide a good template for the introductionar material of the remaining subsubsections? That is, should I introduce define all the problems mathematically before they are discussed in more detail, or are we assuming that the reader is familiar with these standard types of problems?

**Comment by antonior92** [comment]
> Is this an appropriate way of breaking down the optimization subsection?

I liked it. It gives a good notion of what needs to be done. Maybe we can merge a few subsections later on.

> Does the introductory text written for root finding provide a good template for the introductionar material of the remaining subsubsections? That is, should I introduce define all the problems mathematically before they are discussed in more detail, or are we assuming that the reader is familiar with these standard types of problems?


I think we should try to define mathematically the most important problems.

Since the paper will discuss very diverse topics, it is very likely that the reader does not know deeply about many of them. So I think we should not expect that the reader has a background on the subject. Maybe we could try to delegate more complicated concepts (like *local* and *global convergence* in my PR) to tables, figures and footnotes.

**Comment by rgommers** [comment]
In general I think that there are too many sub-sections here. We shouldn't try to cover all the functionality that `optimize` has to offer, just focus on the highlights / recent improvements (which I'd say are the methods behind `minimize` and `linprog` only).

**Comment by mdhaber** [comment]
@antonior92 I want to leave out the description of the problem for now. The reason is that I want to put the content of #17 alongside this so we can better judge what sorts of things we like about each and decide how to unify them, as the fact that #17 has the mathematical problem statement and #16 doesn't is just one of many significant differences. If that sounds good, please merge this and #17. Then, I'll write a post in #13 listing these differences and asking for feedback on how we can resolve them so that we have a more unified paper.

**Comment by mdhaber** [comment]
@rgommers in #13 I had a table of "recent" improvements that I thought we might include. Based on that, @surhudm had contributed a bit about `curve_fit`, @andyfaff was going to write about global optimizers, I've been trying to contact @larsmans about linear sum assignment, and I was considering asking @pv about the addition of `df-sane` to `root`. Should these be left out?

**Comment by rgommers** [comment]
> ...  Should these be left out?

I think so. Just based on space requirements: if we include all those types of things, we're going to end up with a 30+ page paper (which won't be acceptable to the journal very likely). They would be great for a more in-depth article on `scipy.optimize`, but here I think we should focus on a selection of the most important changes only.

**Pull request merged**
