### PR TITLE
Move Roadmap into Future Work subsection

### PR DESCRIPTION
**Pull request by tylerjereddy**
For checklist items from #65:

- Future development
  - Condense the PyData sparse content a little maybe & update if appropriate given any recent roadmap / plan adjustments?
  - there is nothing else in this section -- perhaps just refer back to the roadmap then, or combine roadmap and future directions somehow??

I think the easiest solution here is to remove the "Future Development" section--it is redundant with the preceding "Roadmap" section, which already correctly mentions Hameer's sparse package.

Roadmap section may need updates, but on the other hand we would technically be referring to the roadmap from 1.0 instead of *now*, so just a short table citing the real thing may suffice there anyway (separate checklist item).

### CODE REVIEW

**Comment by mdhaber** [comment]
This is a tough one. The roadmap section makes sense where it is, and the future development section was like "future work" which is usually in a discussion toward the end of a paper. Could the roadmap section be moved toward the end and referred to as "future work"?

**Comment by stefanv** [comment]
On January 24, 2019 18:07:33 Matt Haberland <notifications@github.com> wrote:
> This is a tough one. The roadmap section makes sense where it is, and the 
> future development section was like "future work" which is usually in a 
> discussion toward the end of a paper. Could the roadmap section be moved 
> toward the end and referred to as "future work"?
That works.

**Comment by tylerjereddy** [comment]
Ok, I moved the roadmap content into the Future Work subsection based on feedback above, instead of the original intent of deleting the Future Work section.

Depending on decisions / merge orders, converting the roadmap to a table in a separate PR may generate some merge conflict issues, but we can deal with that if / when it happens.

**Comment by tylerjereddy** [comment]
Ok, I've followed the suggestions of two core developers here and no other comments in the last week so will self-merge in the spirit of keeping the revisions moving forward so we can submit sooner than later.

**Comment by mdhaber** [comment]
Thanks again. Been a very busy week.

**Pull request merged**
