### PR TITLE
Add a section on the scope of SciPy

### PR DESCRIPTION
**Pull request by rgommers**
I know that citations for other packages are missing, I want to leave that out for now. @jarrodmillman already has a bunch in his BibTeX file, and we can go through at the end for consistent citing.

### CODE REVIEW

**Comment by ev-br** [comment]
Let's keep the ball rolling. Thanks Ralf.

**Comment by rgommers** [comment]
Thanks @mdhaber. Your comments just crossed with the merge, so pushed your corrections to master in 7769c10.

**Comment by mdhaber** [comment]
@rgommers These (and other recent comments on already-merged PRs) were intended to be suggestions for the author to consider; I don't think I will make the changes directly.

**Comment by rgommers** [comment]
Yes I know. I took them as suggestions, and made the changes.

**Comment by mdhaber** [comment]
@rgommers Oops I misread.

**Pull request merged**
