### PR TITLE
Small reorganization of non-linear optimization section

### PR DESCRIPTION
**Pull request by stsievert**
Thanks for the nice work on this paper. I've read through it, and have a small reorganization for the optimize section.

This PR doesn't do much after reading through #102 and #130. It references the table earlier (which is nice for references) and splits the paragraphs in two.

### CODE REVIEW

**Comment by mdhaber** [comment]
I'd merge 0e77cc4 without hesitation. 139c66e seems to be a matter of preference; I can't tell if there's something objective it is trying to fix? I can't merge that unless others agree it is an improvement.

**Comment by stsievert** [comment]
I started 139c66e because it wasn't clear where to find the citations for `trust-*` and `dogleg` when reading the first time – I had to get to the end of the paragraph before finding the table reference.

In 91290e7, I've also added the citations directly in the paragraph for `trust-*` and `dogleg`.

**Comment by tylerjereddy** [comment]
> This PR doesn't do much

I'll leave it up to Matt's judgement then maybe -- I'm going to start to check out the submission website & so on because we'd like to get this submitted today (!)

**Comment by mdhaber** [comment]
I'm not sure on this one, either. Since the functions themselves are not documented in these references, it is not clear that these references belong here. For now I'll fix the `@` operator in a new PR.

**Comment by rgommers** [comment]
this looks fine to me, maybe a tiny improvement on the current version. hard to see without putting pdf's of old and new side to side.

**Comment by mdhaber** [comment]
Thanks for this @stsievert but I think I'll close as we're preparing to resubmit. Please fix merge conflicts and re-open if you feel strongly, though.

**Pull request closed without merging**
