### PR TITLE
Fix formatting of Refs in Table 1

### PR DESCRIPTION
**Pull request by FabricioS**
See #214

### CODE REVIEW

**Comment by ilayn** [comment]
This PR 
image

Compared to previous
image

I agree it is nicer. However I am not really a fan of the slanted column names. I think typewriter font is not needed there since there is no other context and slanting seems not to help on readability.

**Comment by mdhaber** [comment]
@FabricioS Thanks for this. I noticed this issue recently but didn't take the time to figure out how to fix it, so I appreciate it. 

@ilayn I think I adjusted the angle of the column names at one point. The reason I didn't go with pure vertical was that it made the table look squashed horizontally, but again, I didn't take the time to figure out how to adjust the angle and column width independently. If you can show my another option (in another PR), I'd be happy to take a look.

**Comment by mdhaber** [comment]
Thanks @FabricioS!

**Comment by mdhaber** [comment]
Closes #214

**Pull request merged**
