### PR TITLE
Remove unnecessary mention of CPython

### LINKED ISSUE #223: Comment to Address: Technical Details
>  Page 2. A clear distinction between CPython and Python is stressed, which might not be relevant to many audiences as alternatives like PyPI are likely not well understood. This is also an example of where the paper may delve too much into technical details.

### PR DESCRIPTION
**Pull request by mdhaber**
Closes #223

### CODE REVIEW

**Comment by tylerjereddy** [comment]
thanks Matt

**Comment by mdhaber** [comment]
Thanks. We need to make sure this doesn't appear in the second arXiv submission though.

**Comment by tylerjereddy** [comment]
I assume the backports will be up until just before the first *Nature Methods* revision is merged

**Comment by mdhaber** [comment]
IIRC a publisher I'd worked with in the past didn't allow posting a manuscript that Incorporated reviewer comments. I see now that policies vary quite a bit, and Nature Methods does not seem to forbid that. Their policy is [here](https://www.nature.com/articles/nmeth.3831).

**Pull request merged**
