### PR TITLE
DOC: update README with article types, repo organization, authorship policy

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
@stefanv I read the discussion on the scikit-image list about how you constructed the author list for your paper, but it was inconclusive. Looking back, any recommendations you would make?

**Comment by stefanv** [comment]
@rgommers With that paper, we added everyone who contributed substantially to the paper as authors, and credited everyone else as "the scikit-image contributors".  The ordering of the list was more-or-less on a first come basis.

I guess some of us needed the paper more than others, hence the names, otherwise I may just have gone with "the scikit-image contributors".

**Comment by rgommers** [comment]
Thanks Stefan. 

For the SciPy paper, I think we should go with everyone who contributed substantially to the project, not to the paper. The latter wouldn't be very practical even if we'd like that idea, given the large number of contributors.

**Comment by ev-br** [comment]
@rgommers   do you want to add/change something further? I think we should merge this and iterate if necessary.

**Comment by rgommers** [comment]
Let's do that!

**Pull request merged**
