### PR TITLE
Combine potentially redundant information about STScI transition to Python

### LINKED ISSUE #139: Possible repetition of facts about STScI in close proximity?
Right before the SciPy begins section:
"Initial work on numerical computing in Python was driven by graduate students, but soon larger research labs became increasingly engaged. For example, Paul Dubois at Lawrence Livermore National Laboratory (LLNL) took over the maintenance of Numeric and funded the writing of its manual[19], and in 1998 the Space Telescope Science Institute (STScI), which was in charge of Hubble Space Telescope science operations, decided to replace their custom scripting language with Python[20].

The third paragraph of SciPy begins:
"At this point, scientific Python started attracting more serious attention; code that started out as side projects by graduate students has grown into essential infrastructure at national laboratories and research institutes. For example, starting in 2000, STScI ported their IDL-based analysis pipeline, IRAF, to Python."

I can't tell whether the facts about the 1998 replacement of custom scripting language to the 2000 porting of the analysis pipeline are distinct. They are both prefaced with the idea that work started by graduate students become important at national labs, and they appear within half a page of one another, so I thought I should check.

In any case, I propose combining the two into the third paragraph of SciPy Begins. As I'm doing a "final" readthrough before release for wide review, I'm holding back my thoughts on erroneous commas etc., but I think this is important enough to bring up.

### PR DESCRIPTION
**Pull request by mdhaber**
Closes #139

### CODE REVIEW

**Comment by stefanv** [comment]
This change removes an important emphasis on the role of graduate students in development. Please make sure that emphasis is captured elsewhere.

/cc @jarrodmillman

**Comment by stefanv** [comment]
Yes, looking at this change again, it removes the sentence that provides continuity in the story line. Fine to react the examples, but keep the story in tact?

**Comment by rgommers** [comment]
A meta comment: this history has an unbalanced focus on the very early years, and zero on post 2012. The actual maturing only started around 2009-2019 imho (e.g. scipy was almost completely undocumented until then). None of the main contributors of the last 10 years are mentioned by name either in the history. So in general +1 on compacting the first section a bit.

That said, I cannot volunteer for a rewrite/extension right now, and we really need to get this out the door. So minimal changes would be good at this point.

**Comment by mdhaber** [comment]
@stefanv I don't understand - it retained "At this point, scientific Python started attracting more serious attention; code that started out as side projects by graduate students has grown into
essential infrastructure at national laboratories and research institutes."

Besides this, the emphasis on the role of graduate students in the development is definitely already captured, as in the first two pages there is already:
"When started, the library had little funding, and was written mainly
by graduate students---many of them without a computer science education, and often without the
blessing of their advisors."
"In 1995, Jim Hugunin, a graduate student from MIT, wrote the first
message in a new Python Matrix Special Interest Group (Matrix-SIG)
mailing list"
"A number of these packages were written by graduate students and
postdoctoral researchers to solve the very practical research problems
that they faced on a daily basis."
"Eric Jones, while a graduate student at Duke, wrote a number of
packages to support his dissertation, including a parallel job
scheduler and genetic optimizer."

I only proposed removing the fifth of these six mentions:
"Initial work on numerical computing in Python was driven by graduate
students, but soon larger research labs became increasingly engaged."
This seemed to say the same thing as the one I retained.

**Comment by mdhaber** [comment]
@stefanv The similarity in the bits emphasizing the role of graduate students was actually why I thought the bits about STScI might not be distinct. It's not uncommon for different versions of paragraphs to be commented out and moved around while drafting. I really thought these might be two version of the same paragraph.

> Initial work on numerical computing in Python was driven by graduate
students, but soon larger research labs became increasingly engaged.
For example, Paul Dubois at Lawrence Livermore National Laboratory (LLNL) took over the
maintenance of Numeric and funded the writing of its
manual\cite{Numeric-manual}, and in 1998 the Space Telescope Science Institute (STScI), which was in charge of Hubble Space Telescope science operations, decided to replace their
custom scripting language with Python\cite{STScI-slither}.

>At this point, scientific Python started attracting more serious attention;
code that started out as side projects by graduate students has grown into
essential infrastructure at national laboratories and research institutes.
For example, starting in 2000, STScI ported their IDL-based analysis pipeline,
IRAF, to Python.

Is just condensed this:
> At this point, scientific Python started attracting more serious attention;
code that started out as side projects by graduate students has grown into
essential infrastructure at national laboratories and research institutes. For 
example, Paul Dubois at Lawrence Livermore National Laboratory (LLNL) took 
over the maintenance of Numeric and funded the writing of its manual
\cite{Numeric-manual}, and the Space Telescope Science Institute (STScI), 
which was in charge of Hubble Space Telescope science operations, decided 
to replace their custom scripting language and analysis pipeline with Python
\cite{STScI-slither}.

**Comment by charris** [comment]
> decided to replace their custom scripting language and analysis pipeline with Python

My recollection was that Python was used for prototyping and the actual pipelines were implemented in C++. Might be worth checking.

**Comment by stefanv** [comment]
@mdhaber Thanks for clarifying. I may have looked at a partial diff, sorry. 

@rgommers It would be fair to add more about later history; it's perhaps just trickier to get a firm hold on it. But I'd be happy to review any suggested updates and help fit it into the storyline.

**Comment by rgommers** [comment]
Thanks Stefan. I'm traveling most of this week, and new work tends to pile up during traveling, so I can't promise anything. Let's just continue as planned; perhaps an imminent submission will spur me into last-minute action:)

**Comment by rgommers** [comment]
Read the whole section, I think it reads well and nothing essential seems to be lost. There's still three mentions of STScI, which is enough. So merging. Thanks @mdhaber

**Pull request merged**
